apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bff-service
spec:
  hosts:
    - "api-sandbox.z.inc"
  gateways:
    - app-gateway
  http:
    - name: "bff-service"
      match:
        - uri:
            prefix: /api/v1/bff
      route:
        - destination:
            host: bff-v1
            port:
              number: 3000